### ISSUE TITLE
Small docs update

### ISSUE THREAD

**Issue by kayvonf** [phanrahan/magmathon#15]
Docs for Counter circuit definition seem to be out of date.  They describe the parameter has_r, but parameter name in actual definition is "has_reset" (https://github.com/phanrahan/mantle/blob/master/mantle/common/counter.py)

**Comment by leonardt** [comment]
Fixed by https://github.com/phanrahan/mantle/commit/64673377ab6cf65f666b62e8c50fd0a4856c412e#diff-b99001fd4293cc29a03bd615c0323499, thanks
