### ISSUE TITLE
Adder Simulator

### ISSUE THREAD

**Issue by adamdai** [phanrahan/magmathon#19]
I am trying to simulate an Add circuit with the following code:
```
from magma import *
set_mantle_target("ice40")
from mantle import*
from magma.simulator import PythonSimulator

Add = DefineAdd(8)
print(Add)
add_sim = PythonSimulator(Add)

high = uint(0x01,8)
low = uint(0x03,8)

add_sim.set_value(Add.I0, high)
add_sim.set_value(Add.I1, low)
print(add_sim.get_value(Add.O))
```
I expect to get `0x04` as output in bits form, but instead I get `[False, False, False, False, False, False, False, False]` (it seems python interprets the 1s as `False`). Am I doing something wrong here?

**Comment by leonardt** [comment]
Sorry, the documentation is not very clear about this. You need to call simulator.evaluate() for it to propagate the new inputs. set_value will update the input values, but won't execute the circuit. If/when you move onto a sequential circuit, you can use simulator.advance() which is a combination of half stepping the clock (going from 0 to 1 or 1 to 0) and evaluate.

This file describes the interface https://github.com/phanrahan/magma/blob/master/magma/simulator/simulator.py

Here's a test that shows how to use it with basic combinational logic https://github.com/phanrahan/magma/blob/master/tests/test_simulator/test_logic.py
