### ISSUE TITLE
Provide install script for icestorm tool chain?

### ISSUE THREAD

**Issue by leonardt** [phanrahan/magmathon#2]
We made one for the last hackathon: https://github.com/phanrahan/magma/blob/master/notebooks/icestick/install.py

The benefit is a one click solution for most people, the downside is that if it breaks, it can be more challenging to resolve the issue (compared to when a person is manually stepping through the install process for their specific system).

If we do plan to use this, we should test it both on macos and linux. We could also try it on a linux VM and see if we can get that working (for windows users)

**Comment by leonardt** [comment]
Looks like a initialized a vagrant script we could use for VM support https://github.com/phanrahan/magma/blob/master/notebooks/icestick/Vagrantfile

Note: these files should be extracted from the main magma repository and moved over here to keep things better organized.

**Comment by leonardt** [comment]
It looks like you've already moved the notebooks over here, so we can remove them from the magma repository?

**Comment by phanrahan** [comment]
Yes, we can remove that from magma.

**Comment by leonardt** [comment]
0a8e4df adds the install_icestorm.py script which supports MacOS+Linux and a note in the README.md

This script should be validated on a fresh MacOS and Linux system.

**Comment by phanrahan** [comment]
Can we close this issue?

**Comment by leonardt** [comment]
I left it open because I want to run a sanity check where I go through the install process on a fresh mac/linux environment, but I'll open a specific issue to do this.
