### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by phanrahan** [phanrahan/magmathon#5]
We have two versions of the Install instructions. One is a jupyter notebook and the other is the top level README.md. I suggest we consolidate and just one version.

I vote for the README.md since this can all be done nicely with command line tools.

Note also that the tests directory contains only a single example` blink.py`

**Comment by phanrahan** [comment]
Thanks for updating the install instructions. The README looks good.

I wonder if we should just use make for building everything? That will eliminate one install dependency.

**Comment by leonardt** [comment]
Looks like you updated it to use `make` so I think we can resolve this issue and open new ones as they come up. At some point it would be good to have someone else review the installation flow and provide feedback.
